In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [4]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=32)

## Scaling

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[ 1.11369962,  0.32228604,  1.07850587, ...,  1.28735999,
         0.23491182,  0.02863219],
       [ 0.0504453 , -0.24584785, -0.01954056, ..., -0.59926636,
        -0.43000188, -0.41418997],
       [ 1.51562685, -0.24356619,  1.46682929, ...,  1.71691128,
         1.06605395, -0.35475435],
       ...,
       [-0.49115878,  0.58239553, -0.49213842, ...,  0.09914077,
         0.09691086,  0.43450788],
       [-0.67929493, -0.0313716 , -0.71728338, ..., -0.87569343,
         0.9045301 , -0.79864743],
       [-1.08122217,  1.90804128, -1.07503665, ..., -0.35250614,
        -1.07296089, -0.08916814]])

In [11]:
X_train.shape

(455, 30)

In [12]:
y_train.unique()

array(['M', 'B'], dtype=object)

## Label Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0])

Numpy to pytorch Tensors

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
X_train_tensor.dtype

torch.float64

In [18]:
y_train_tensor = y_train_tensor.float()

In [19]:
X_test_tensor.dtype

torch.float64

In [20]:
torch.rand(2,1)

tensor([[0.4536],
        [0.4517]])

In [21]:
torch.zeros(1)

tensor([0.])

## Defining Dataset and Dataloader class

In [22]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return len(self.features)

    def __getitem__(self,idx):
        return self.features[idx],self.labels[idx]
    

In [23]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [24]:
#dataloader
train_dataloader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_dataloader = DataLoader(test_dataset,batch_size=32,shuffle=True)


## Defining Model

Lets say it has single neuron in single layer(perceptron):

we have 30 columns in X_train so it must have 30 weights and 1 bias


In [25]:
import torch.nn as nn

In [26]:
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network =nn.Sequential(
            nn.Linear(num_features,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        y_pred = self.network(features)
        return y_pred

    


## Important Parameters


In [27]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [34]:

# create model
model = MySimpleNN(X_train_tensor.shape[1])

#define loss function
loss_function = nn.BCELoss()  #Binary Cross Entropy Loss

#define optimizer here sgd
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):
  for batch_features,batch_labels in train_dataloader:
    #since nn.Linear only works for float32 here X_train_tensor is in float64 so gives error so change it
    batch_features = batch_features.float()
    #forward pass
    y_pred = model(batch_features)
  
    # loss calculate
    # y_pred is 2d tensor and batch_labels is 1d tensor so we need to reshape it otherwise it can give diff dim error
    loss = loss_function(y_pred,batch_labels.view(-1,1))

    #zero gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    #parameters update
    optimizer.step()

    #print loss in each epoch
  print(f'Epoch: {epoch+1},Loss: {loss.item()}')



Epoch: 1,Loss: 0.09728320688009262
Epoch: 2,Loss: 0.11130122095346451
Epoch: 3,Loss: 0.2401900589466095
Epoch: 4,Loss: 0.1118452176451683
Epoch: 5,Loss: 0.03550740331411362
Epoch: 6,Loss: 0.15452229976654053
Epoch: 7,Loss: 0.08449484407901764
Epoch: 8,Loss: 0.018211068585515022
Epoch: 9,Loss: 0.029844980686903
Epoch: 10,Loss: 0.07217820733785629
Epoch: 11,Loss: 0.09132417291402817
Epoch: 12,Loss: 0.01534220576286316
Epoch: 13,Loss: 0.1421581506729126
Epoch: 14,Loss: 0.02789771743118763
Epoch: 15,Loss: 0.025376494973897934
Epoch: 16,Loss: 0.005144341848790646
Epoch: 17,Loss: 0.003007507184520364
Epoch: 18,Loss: 0.011519440449774265
Epoch: 19,Loss: 0.006553367245942354
Epoch: 20,Loss: 0.2019210159778595
Epoch: 21,Loss: 0.3527562618255615
Epoch: 22,Loss: 0.012715285643935204
Epoch: 23,Loss: 0.013119732029736042
Epoch: 24,Loss: 0.14285945892333984
Epoch: 25,Loss: 0.04719027504324913


In [29]:
model.network[0].weight

Parameter containing:
tensor([[ 0.4106,  0.5764,  0.6473,  0.4894,  0.2066,  0.0389,  0.3539,  0.5865,
          0.1491, -0.2993,  0.7418,  0.0471,  0.3011,  0.4212,  0.0482, -0.3013,
         -0.1335,  0.0526, -0.1147, -0.1966,  0.6762,  0.6257,  0.5772,  0.7886,
          0.4599,  0.1147,  0.5952,  0.6527,  0.3602,  0.1574]],
       requires_grad=True)

In [30]:
model.network[0].weight.grad 

tensor([[-0.0197, -0.0398, -0.0174, -0.0104,  0.0237, -0.0010,  0.0233,  0.0220,
          0.0164, -0.0008,  0.0392,  0.0723,  0.0410,  0.0259,  0.0681,  0.0357,
          0.0251,  0.0510,  0.0580,  0.0264, -0.0193, -0.0204, -0.0124, -0.0109,
          0.0061, -0.0256, -0.0244, -0.0082, -0.0234, -0.0390]])

In [31]:
model.network[0].bias

Parameter containing:
tensor([-0.4271], requires_grad=True)

## Evaluation

model.eval() tells PyTorch that the model is in inference mode, which:

Disables Dropout → Ensures neurons are not randomly dropped.
Freezes Batch Normalization statistics → Uses running mean/variance instead of mini-batch stats.

In [ ]:
# model evaluation using test_loader
model.eval()  #set the model to evaluation mode removes dropouts and batch_norm
accuracy_list=[]
with torch.no_grad():
  for batch_features,batch_labels in test_dataloader:
    batch_features = batch_features.float()
    #forward pass
    y_pred = model.forward(batch_features)
    y_pred = (y_pred >0.5).float() #convert to 0 and 1

    #compute accuracy
    batch_accuracy = (y_pred == batch_labels.view(-1,1)).float().mean().item()
    accuracy_list.append(batch_accuracy)



#print overall accuracy
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')



Accuracy: 0.9922
