In [2]:
#Next word predictor is used in keypad of phone to suggest next word

Language Modeling : is the task of predicting the next word(or character) in a sequence based on the context of previous words.<br>


steps: 
1) Data Preprocessing <br>
2) Model <br>
3) Training Loop <br>
4) Prediction <br>


Previously we made our own tokenizer function for breaking down text into smaller units called tokens — which are the basic building blocks that a language model or NLP system understands.



Now we'll use nltk for it 

In [3]:
import torch
import nltk
from nltk.tokenize import word_tokenize
from torch.utils.data import Dataset,DataLoader
import torch.nn as nn

In [4]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [5]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [6]:
#tokenize
tokens = word_tokenize(document.lower())
tokens

['about',
 'the',
 'program',
 'what',
 'is',
 'the',
 'course',
 'fee',
 'for',
 'data',
 'science',
 'mentorship',
 'program',
 '(',
 'dsmp',
 '2023',
 ')',
 'the',
 'course',
 'follows',
 'a',
 'monthly',
 'subscription',
 'model',
 'where',
 'you',
 'have',
 'to',
 'make',
 'monthly',
 'payments',
 'of',
 'rs',
 '799/month',
 '.',
 'what',
 'is',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 '?',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 'is',
 '7',
 'months',
 '.',
 'so',
 'the',
 'total',
 'course',
 'fee',
 'becomes',
 '799',
 '*',
 '7',
 '=',
 'rs',
 '5600',
 '(',
 'approx',
 '.',
 ')',
 'what',
 'is',
 'the',
 'syllabus',
 'of',
 'the',
 'mentorship',
 'program',
 '?',
 'we',
 'will',
 'be',
 'covering',
 'the',
 'following',
 'modules',
 ':',
 'python',
 'fundamentals',
 'python',
 'libraries',
 'for',
 'data',
 'science',
 'data',
 'analysis',
 'sql',
 'for',
 'data',
 'science',
 'maths',
 'for',
 'machine',
 'learning',
 'ml',
 'algorithms',
 'p

In [7]:
#unique tokens (alphabetically sorted)
tokens = list(sorted(set(tokens)))
tokens

['(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '//docs.google.com/spreadsheets/d/16ootax_a6oraecg4emgexhqqpv3noqpyku7rj6arozk/edit',
 '//learnwith.campusx.in/',
 '//learnwith.campusx.in/courses/campusx-data-science-mentorship-program-637339afe4b0615a1bbed390',
 '1',
 '15th',
 '1st',
 '2',
 '2023',
 '2024.',
 '20th',
 '21st',
 '30',
 '5600',
 '7',
 '799',
 '799/month',
 ':',
 '=',
 '?',
 '@',
 'a',
 'able',
 'about',
 'absolutely',
 'afraid',
 'after',
 'again',
 'algorithms',
 'all',
 'am',
 'amount',
 'analysis',
 'and',
 'any',
 'anytime',
 'approx',
 'are',
 'ask',
 'assessments',
 'assistance',
 'at',
 'attempt',
 'aug',
 'back',
 'background',
 'be',
 'because',
 'become',
 'becomes',
 'before',
 'both',
 'building',
 'but',
 'by',
 'calls',
 'can',
 'carefully',
 'case',
 'certificate',
 'channel',
 'check',
 'checkout',
 'clarify',
 'class',
 'clearance',
 'comes',
 'contact',
 'content',
 'course',
 'covering',
 'criteria',
 'criterias',
 'current',
 'curriculum',
 'dashboard',
 'data',


In [8]:
#build vocab
vocab ={'<unk>':0}

for token in tokens:
    if token not in vocab:
        vocab[token]=len(vocab)

vocab



{'<unk>': 0,
 '(': 1,
 ')': 2,
 '*': 3,
 ',': 4,
 '-': 5,
 '.': 6,
 '//docs.google.com/spreadsheets/d/16ootax_a6oraecg4emgexhqqpv3noqpyku7rj6arozk/edit': 7,
 '//learnwith.campusx.in/': 8,
 '//learnwith.campusx.in/courses/campusx-data-science-mentorship-program-637339afe4b0615a1bbed390': 9,
 '1': 10,
 '15th': 11,
 '1st': 12,
 '2': 13,
 '2023': 14,
 '2024.': 15,
 '20th': 16,
 '21st': 17,
 '30': 18,
 '5600': 19,
 '7': 20,
 '799': 21,
 '799/month': 22,
 ':': 23,
 '=': 24,
 '?': 25,
 '@': 26,
 'a': 27,
 'able': 28,
 'about': 29,
 'absolutely': 30,
 'afraid': 31,
 'after': 32,
 'again': 33,
 'algorithms': 34,
 'all': 35,
 'am': 36,
 'amount': 37,
 'analysis': 38,
 'and': 39,
 'any': 40,
 'anytime': 41,
 'approx': 42,
 'are': 43,
 'ask': 44,
 'assessments': 45,
 'assistance': 46,
 'at': 47,
 'attempt': 48,
 'aug': 49,
 'back': 50,
 'background': 51,
 'be': 52,
 'because': 53,
 'become': 54,
 'becomes': 55,
 'before': 56,
 'both': 57,
 'building': 58,
 'but': 59,
 'by': 60,
 'calls': 61,
 'can

In [9]:
len(vocab)

289

In [10]:
# extract sentences from data
input_sentences = document.split('\n')
input_sentences


['About the Program',
 'What is the course fee for  Data Science Mentorship Program (DSMP 2023)',
 'The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.',
 'What is the total duration of the course?',
 'The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)',
 'What is the syllabus of the mentorship program?',
 'We will be covering the following modules:',
 'Python Fundamentals',
 'Python libraries for Data Science',
 'Data Analysis',
 'SQL for Data Science',
 'Maths for Machine Learning',
 'ML Algorithms',
 'Practical ML',
 'MLOPs',
 'Case studies',
 'You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390',
 'Will Deep Learning and NLP be a part of this program?',
 'No, NLP and Deep Learning both are not a part of this program’s curriculum.',
 'What if I miss a live session? Will I get a recording 

In [11]:
for sentence in input_sentences:
    print(word_tokenize(sentence.lower()))

['about', 'the', 'program']
['what', 'is', 'the', 'course', 'fee', 'for', 'data', 'science', 'mentorship', 'program', '(', 'dsmp', '2023', ')']
['the', 'course', 'follows', 'a', 'monthly', 'subscription', 'model', 'where', 'you', 'have', 'to', 'make', 'monthly', 'payments', 'of', 'rs', '799/month', '.']
['what', 'is', 'the', 'total', 'duration', 'of', 'the', 'course', '?']
['the', 'total', 'duration', 'of', 'the', 'course', 'is', '7', 'months', '.', 'so', 'the', 'total', 'course', 'fee', 'becomes', '799', '*', '7', '=', 'rs', '5600', '(', 'approx', '.', ')']
['what', 'is', 'the', 'syllabus', 'of', 'the', 'mentorship', 'program', '?']
['we', 'will', 'be', 'covering', 'the', 'following', 'modules', ':']
['python', 'fundamentals']
['python', 'libraries', 'for', 'data', 'science']
['data', 'analysis']
['sql', 'for', 'data', 'science']
['maths', 'for', 'machine', 'learning']
['ml', 'algorithms']
['practical', 'ml']
['mlops']
['case', 'studies']
['you', 'can', 'check', 'the', 'detailed', 'sy

In [12]:
def text_to_indices(sentence,vocab):
    numerical_sentence = []
    for token in sentence:
        if token in vocab:
            numerical_sentence.append(vocab[token])
        else:
            numerical_sentence.append(vocab['<unk>'])
    return numerical_sentence

In [13]:
input_numerical_sentences = []
for sentence in input_sentences:
    input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()),vocab))

In [14]:
input_numerical_sentences

[[29, 253, 206],
 [277, 138, 253, 75, 107, 112, 82, 225, 167, 206, 1, 95, 14, 2],
 [253,
  75,
  111,
  27,
  175,
  245,
  172,
  279,
  284,
  122,
  259,
  161,
  175,
  197,
  182,
  222,
  22,
  6],
 [277, 138, 253, 260, 96, 182, 253, 75, 25],
 [253,
  260,
  96,
  182,
  253,
  75,
  138,
  20,
  176,
  6,
  236,
  253,
  260,
  75,
  107,
  55,
  21,
  3,
  20,
  24,
  222,
  19,
  1,
  42,
  6,
  2],
 [277, 138, 253, 247, 182, 253, 167, 206, 25],
 [274, 281, 52, 76, 253, 110, 173, 23],
 [211, 115],
 [211, 151, 112, 82, 225],
 [82, 38],
 [240, 112, 82, 225],
 [163, 112, 158, 149],
 [170, 34],
 [205, 170],
 [171],
 [64, 243],
 [284, 62, 67, 253, 86, 247, 123, 5, 127, 23, 9],
 [281, 85, 149, 39, 178, 52, 27, 192, 182, 256, 206, 25],
 [179,
  4,
  178,
  39,
  85,
  149,
  57,
  43,
  181,
  27,
  192,
  182,
  256,
  206,
  288,
  223,
  80,
  6],
 [277,
  130,
  129,
  169,
  27,
  155,
  230,
  25,
  281,
  129,
  116,
  27,
  217,
  182,
  253,
  230,
  25],
 [283,
  35,
  187,

In [15]:
len(input_numerical_sentences)

78

Converting into training sequences <br>
ie converting [1,2,3] into [1,2],[1,2,3]

In [16]:
training_sequence = []
for sentence in input_numerical_sentences:
    for i in range(1,len(sentence)):
        training_sequence.append(sentence[:i+1])
        
    

In [17]:
training_sequence

[[29, 253],
 [29, 253, 206],
 [277, 138],
 [277, 138, 253],
 [277, 138, 253, 75],
 [277, 138, 253, 75, 107],
 [277, 138, 253, 75, 107, 112],
 [277, 138, 253, 75, 107, 112, 82],
 [277, 138, 253, 75, 107, 112, 82, 225],
 [277, 138, 253, 75, 107, 112, 82, 225, 167],
 [277, 138, 253, 75, 107, 112, 82, 225, 167, 206],
 [277, 138, 253, 75, 107, 112, 82, 225, 167, 206, 1],
 [277, 138, 253, 75, 107, 112, 82, 225, 167, 206, 1, 95],
 [277, 138, 253, 75, 107, 112, 82, 225, 167, 206, 1, 95, 14],
 [277, 138, 253, 75, 107, 112, 82, 225, 167, 206, 1, 95, 14, 2],
 [253, 75],
 [253, 75, 111],
 [253, 75, 111, 27],
 [253, 75, 111, 27, 175],
 [253, 75, 111, 27, 175, 245],
 [253, 75, 111, 27, 175, 245, 172],
 [253, 75, 111, 27, 175, 245, 172, 279],
 [253, 75, 111, 27, 175, 245, 172, 279, 284],
 [253, 75, 111, 27, 175, 245, 172, 279, 284, 122],
 [253, 75, 111, 27, 175, 245, 172, 279, 284, 122, 259],
 [253, 75, 111, 27, 175, 245, 172, 279, 284, 122, 259, 161],
 [253, 75, 111, 27, 175, 245, 172, 279, 284, 122

In [18]:
len(training_sequence)

942

padding zeros for batch training

In [19]:
#longest seq 
len_list = []
for sequence in training_sequence:
    len_list.append(len(sequence))

In [20]:
max(len_list)

62

In [21]:
padded_training_seq = []
for sequence in training_sequence:
    padded_training_seq.append([0]*(max(len_list)-len(sequence)) + sequence)

padded_training_seq

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  29,
  253],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  29,
  253,
  206],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  277,
  138],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [22]:
len(padded_training_seq)
len(padded_training_seq[0])

62

In [23]:
padded_training_seq = torch.tensor(padded_training_seq,dtype = torch.long)

In [24]:
padded_training_seq

tensor([[  0,   0,   0,  ...,   0,  29, 253],
        [  0,   0,   0,  ...,  29, 253, 206],
        [  0,   0,   0,  ...,   0, 277, 138],
        ...,
        [  0,   0,   0,  ...,  88, 183, 140],
        [  0,   0,   0,  ..., 183, 140, 128],
        [  0,   0,   0,  ..., 140, 128, 242]])

In [25]:
padded_training_seq.shape

torch.Size([942, 62])

In [26]:
X = padded_training_seq[:,:-1]
y = padded_training_seq[:,-1]

In [27]:
X

tensor([[  0,   0,   0,  ...,   0,   0,  29],
        [  0,   0,   0,  ...,   0,  29, 253],
        [  0,   0,   0,  ...,   0,   0, 277],
        ...,
        [  0,   0,   0,  ...,   0,  88, 183],
        [  0,   0,   0,  ...,  88, 183, 140],
        [  0,   0,   0,  ..., 183, 140, 128]])

In [28]:
y

tensor([253, 206, 138, 253,  75, 107, 112,  82, 225, 167, 206,   1,  95,  14,
          2,  75, 111,  27, 175, 245, 172, 279, 284, 122, 259, 161, 175, 197,
        182, 222,  22,   6, 138, 253, 260,  96, 182, 253,  75,  25, 260,  96,
        182, 253,  75, 138,  20, 176,   6, 236, 253, 260,  75, 107,  55,  21,
          3,  20,  24, 222,  19,   1,  42,   6,   2, 138, 253, 247, 182, 253,
        167, 206,  25, 281,  52,  76, 253, 110, 173,  23, 115, 151, 112,  82,
        225,  38, 112,  82, 225, 112, 158, 149,  34, 170, 243,  62,  67, 253,
         86, 247, 123,   5, 127,  23,   9,  85, 149,  39, 178,  52,  27, 192,
        182, 256, 206,  25,   4, 178,  39,  85, 149,  57,  43, 181,  27, 192,
        182, 256, 206, 288, 223,  80,   6, 130, 129, 169,  27, 155, 230,  25,
        281, 129, 116,  27, 217, 182, 253, 230,  25,  35, 187, 231,  43, 216,
          4, 236, 103, 130, 284, 169,  27, 230, 284,  62, 119,  50,  39, 273,
        253, 217,   6,  62, 129, 109, 253,  70, 224,  25, 256, 1

In [29]:
class CustomDataset(Dataset):
    def __init__(self,X,y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self,idx):
        return self.X[idx],self.y[idx]

In [30]:
dataset = CustomDataset(X,y)

In [31]:
len(dataset)

942

In [32]:
dataset[0]

(tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0, 29]),
 tensor(253))

In [33]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)


In [34]:
for input,output in dataloader:
    print(input,output)
    print(input.shape,output.shape)
    break

tensor([[  0,   0,   0,  ..., 192, 182, 256],
        [  0,   0,   0,  ..., 149,  39, 178],
        [  0,   0,   0,  ...,  33, 183,  12],
        ...,
        [  0,   0,   0,  ..., 249, 182, 253],
        [  0,   0,   0,  ..., 175, 245, 172],
        [  0,   0,   0,  ..., 288, 248, 153]]) tensor([206,  52, 105,  52, 287,   2, 233, 161,   6,  59, 187,  90,   4,   5,
        288, 122, 230, 172, 138,  21, 131,  60, 284, 189,  49, 176,  12, 235,
        155,  75, 279, 253])
torch.Size([32, 61]) torch.Size([32])


In [35]:
#architecture

class LSTMModel(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,100)
        self.lstm = nn.LSTM(100,150,batch_first=True)
        self.fc = nn.Linear(150,vocab_size)

    def forward(self,x):
        embedded = self.embedding(x)
        intermediate_hidden_states,(final_hidden_state,final_cell_state) =self.lstm(embedded)
        output = self.fc(final_hidden_state.squeeze(0))
        return output

        


In [36]:
len(vocab)

289

In [37]:
#testing layers
x = nn.Embedding(289,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150,289) #289 vocab_size

In [38]:
#taking 
dataset[0][0]
dataset[0][0].shape

torch.Size([61])

In [39]:
#adding one dimension for batch size(say 1)
a = dataset[0][0].unsqueeze(0) #(batch_size,seq_len)

In [40]:
b=x(a) #(batch_size,seq_len,embeddings)

In [41]:
y(b)

(tensor([[[-0.0862,  0.0143,  0.0025,  ..., -0.1974,  0.1835,  0.0333],
          [-0.1204,  0.0008, -0.0310,  ..., -0.3209,  0.2550,  0.0497],
          [-0.1342, -0.0115, -0.0572,  ..., -0.3933,  0.2832,  0.0570],
          ...,
          [-0.1364, -0.0216, -0.0981,  ..., -0.5087,  0.3127,  0.0633],
          [-0.1364, -0.0216, -0.0981,  ..., -0.5087,  0.3127,  0.0633],
          [-0.0376, -0.0141, -0.1758,  ..., -0.1266,  0.0924, -0.0464]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[-0.0376, -0.0141, -0.1758,  0.1625, -0.0034,  0.0401,  0.1239,
            -0.1170,  0.0623, -0.0352, -0.1943, -0.1463,  0.2308, -0.0350,
            -0.0076, -0.1601, -0.0828, -0.0014,  0.0142, -0.0686, -0.0857,
             0.1561,  0.0076,  0.0062, -0.0478,  0.1132,  0.1601,  0.0778,
            -0.1046, -0.1309,  0.1424, -0.2409,  0.0860,  0.0164, -0.0092,
             0.2927, -0.1493,  0.0845, -0.2029,  0.1358, -0.0602, -0.1317,
            -0.1966, -0.1236, -0.0477,  0.0234, -0.0828, -0.07

In [42]:
len(y(b))

2

In [43]:
c,d =y(b)

In [44]:
c.shape #ie intermediate hidden states of all timesteps(batchsize,seq_len,hidden_state_as_out(150))

torch.Size([1, 61, 150])

In [45]:
#d is itself a tuple
len(d)

2

In [46]:
e,f = d

In [47]:
e.shape # final h(t) as final output 
f.shape # final cell state

torch.Size([1, 1, 150])

In [48]:
z(f.squeeze(0)).shape

torch.Size([1, 289])

In [49]:
model = LSTMModel(len(vocab))

In [50]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [51]:
model =model.to(device)

In [52]:
epochs = 50
lr = 0.001

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr= lr)

In [53]:
#training loop
for epoch in range(epochs):
    total_batch_loss = 0
    for batch_x,batch_y in dataloader:
        batch_x,batch_y = batch_x.to(device),batch_y.to(device)
        y_pred = model(batch_x)
        batch_loss = criterion(y_pred,batch_y)

        optimizer.zero_grad()
        batch_loss.backward()

        optimizer.step()

        total_batch_loss +=batch_loss
    print(f"Epoch:{epoch+1},Loss:{total_batch_loss}")


Epoch:1,Loss:165.7996826171875
Epoch:2,Loss:145.6945037841797
Epoch:3,Loss:134.07791137695312
Epoch:4,Loss:121.7841796875
Epoch:5,Loss:110.44843292236328
Epoch:6,Loss:99.04645538330078
Epoch:7,Loss:88.59171295166016
Epoch:8,Loss:78.72000122070312
Epoch:9,Loss:69.65974426269531
Epoch:10,Loss:61.438446044921875
Epoch:11,Loss:54.15919876098633
Epoch:12,Loss:47.623172760009766
Epoch:13,Loss:41.96917724609375
Epoch:14,Loss:36.739707946777344
Epoch:15,Loss:32.08072280883789
Epoch:16,Loss:28.187801361083984
Epoch:17,Loss:24.76849365234375
Epoch:18,Loss:22.206193923950195
Epoch:19,Loss:19.475387573242188
Epoch:20,Loss:17.683917999267578
Epoch:21,Loss:15.731182098388672
Epoch:22,Loss:14.194232940673828
Epoch:23,Loss:13.129133224487305
Epoch:24,Loss:12.07926082611084
Epoch:25,Loss:10.91341495513916
Epoch:26,Loss:10.164770126342773
Epoch:27,Loss:9.445047378540039
Epoch:28,Loss:8.852396011352539
Epoch:29,Loss:8.300675392150879
Epoch:30,Loss:7.985367774963379
Epoch:31,Loss:7.563368320465088
Epoch:3

In [63]:
#prediction 
def prediction(model,vocab,text):
    #tokenize 
    tokenized_text = word_tokenize(text.lower())
    
    #text to numerical indices
    numerical_text = text_to_indices(tokenized_text,vocab)

    #padding
    padded_text = torch.tensor([0]*(62-len(numerical_text)) + numerical_text,dtype = torch.long).unsqueeze(0)
    padded_text = padded_text.to(device)
    #send to model
    output = model(padded_text)
    # print(output.shape)
    #predicted index
    value,index =torch.max(output,dim=1)
    #merge with text 
    return list(vocab.keys())[index]



In [ ]:
prediction(model,vocab,"The Course Follows a monthly")

str

In [69]:
num_tokens = 10
input_text = "who are you"
output_text = input_text
for i in range(num_tokens):
    output = prediction(model,vocab,input_text)
    output_text = output_text + " "+ output 
    input_text = output_text

print(output_text)

    




who are you have to contact us by sending a mail at nitish.campusx


In [57]:
dataloader1 = DataLoader(dataset, batch_size=32, shuffle=False)

In [70]:
#accuracy 
def calculate_accuracy(model):
    model.eval()
    correct = 0
    total =0
    with torch.no_grad():
        for batch_x,batch_y in dataloader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            # Get model predictions
            outputs = model(batch_x)
             # Get the predicted word indices
            _, predicted = torch.max(outputs, dim=1)
            # Compare with actual labels
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)
    
    accuracy = correct / total *100
    return accuracy

#compute accuracy 
accuracy = calculate_accuracy(model)
print("Model Accuracy",accuracy)


Model Accuracy 95.64755838641189
