In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [4]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=32)

## Scaling

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[ 1.11369962,  0.32228604,  1.07850587, ...,  1.28735999,
         0.23491182,  0.02863219],
       [ 0.0504453 , -0.24584785, -0.01954056, ..., -0.59926636,
        -0.43000188, -0.41418997],
       [ 1.51562685, -0.24356619,  1.46682929, ...,  1.71691128,
         1.06605395, -0.35475435],
       ...,
       [-0.49115878,  0.58239553, -0.49213842, ...,  0.09914077,
         0.09691086,  0.43450788],
       [-0.67929493, -0.0313716 , -0.71728338, ..., -0.87569343,
         0.9045301 , -0.79864743],
       [-1.08122217,  1.90804128, -1.07503665, ..., -0.35250614,
        -1.07296089, -0.08916814]])

In [11]:
X_train.shape

(455, 30)

In [12]:
y_train.unique()

array(['M', 'B'], dtype=object)

## Label Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0])

Numpy to pytorch Tensors

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
y_train_tensor.dtype

torch.int64

In [18]:
X_train.dtype

dtype('float64')

In [19]:
torch.rand(2,1)

tensor([[0.0120],
        [0.4047]])

In [20]:
torch.zeros(1)

tensor([0.])

## Defining Model

Lets say it has single neuron in single layer(perceptron):

we have 30 columns in X_train so it must have 30 weights and 1 bias


In [21]:
class MySimpleNN():
  def __init__(self,X):
    self.weights =torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z= torch.matmul(X,self.weights)+ self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_funtion(self,y_pred,y):
    #clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    #Note y_pred is 2d tensor but y is y_train_tensor ie 1d tensor so make it 2 dim by adding 1 dim
    y=y.view(-1,1) #in view we can use -1 to infer the exact shape and 1 to add dim
    #calculate loss
    loss = -(y *torch.log(y_pred) + (1-y)* torch.log(1-y_pred)).mean()
    
    return loss



## Important Parameters


In [22]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [ ]:

# create model
model = MySimpleNN(X_train_tensor)
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)
  print("y_pred",y_pred)
  

  # loss calculate
  loss = model.loss_funtion(y_pred,y_train_tensor)
  print("loss",loss)
  
  # Backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():  # we dont need to track this for gradient
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch+1},Loss: {loss.item()}')



y_pred tensor([[9.9441e-01],
        [2.6877e-05],
        [9.9782e-01],
        [9.7990e-01],
        [1.2218e-06],
        [1.0000e+00],
        [9.9995e-01],
        [9.9995e-01],
        [9.9999e-01],
        [1.0000e+00],
        [7.7578e-02],
        [4.3717e-02],
        [1.0000e+00],
        [2.2183e-05],
        [1.0065e-02],
        [9.9476e-01],
        [1.1852e-07],
        [9.0886e-01],
        [4.7082e-01],
        [3.4201e-02],
        [3.1158e-04],
        [6.9807e-02],
        [9.9792e-01],
        [9.5152e-01],
        [8.5815e-07],
        [1.2132e-05],
        [1.3627e-02],
        [6.9977e-01],
        [9.9999e-01],
        [2.0217e-02],
        [8.5689e-02],
        [4.2377e-01],
        [6.7721e-07],
        [1.3542e-01],
        [1.1808e-03],
        [8.5342e-05],
        [7.8730e-05],
        [2.1495e-02],
        [2.6343e-01],
        [2.1351e-03],
        [9.9999e-01],
        [4.3902e-02],
        [9.9093e-01],
        [1.0000e+00],
        [3.3180e-05],
   

In [24]:
model.weights

tensor([[ 0.9683],
        [ 0.2226],
        [ 0.8403],
        [ 0.5416],
        [-0.0102],
        [ 0.0653],
        [-0.0030],
        [ 0.1190],
        [ 0.4964],
        [ 0.6099],
        [ 0.5365],
        [ 0.0969],
        [ 0.9683],
        [ 0.3568],
        [ 0.5270],
        [ 0.0084],
        [ 0.3481],
        [ 0.6646],
        [ 0.7787],
        [ 0.5248],
        [ 0.2401],
        [ 0.5487],
        [ 0.8684],
        [ 0.3731],
        [ 0.0838],
        [-0.0260],
        [ 0.6821],
        [ 0.4772],
        [ 0.0539],
        [-0.0176]], dtype=torch.float64, requires_grad=True)

In [25]:
model.bias

tensor([-0.0670], dtype=torch.float64, requires_grad=True)

## Evaluation

In [26]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)

#say threshold is 0.5
y_pred = (y_pred > 0.5).float()
accuracy = (y_pred == y_test_tensor).float().mean()
print(f'Accuracy: {accuracy.item()}')



Accuracy: 0.5280086398124695
